#docker image build command
#docker build --rm -t rocm-base-8343 --file <completepath>/Dockerfile <completepath> --no-cache
##uploaded docker image to docker hub
#docker tag 498e66734905  pramenku/tf-rocm#
#docker push pramenku/tf-rocm#


#| This Dockerfile provides a starting point for a ROCm installation of Tensorflow.
#ARG base_image
#FROM ${base_image}

FROM centos:7

MAINTAINER Pramendra Kumar <pramendra.kumar@amd.com>

ARG ROCM_PATH=/opt/rocm
ARG rocm_rel
#ENV DEBIAN_FRONTEND noninteractive
ENV HOME /root/

ADD apt /root/apt
WORKDIR /root/apt
#RUN cp -rf /root/apt/sources.list /etc/apt/
RUN cp -rf /root/apt/resolv.conf /etc/

RUN yum clean all
RUN rm -rf /var/cache/yum/*
# Update centos
#RUN yum -y update
#RUN yum clean all

# Base
RUN yum -y install git java-1.8.0-openjdk python
RUN yum clean all

WORKDIR $HOME
# Enable epel-release repositories
RUN yum --enablerepo=extras install -y epel-release

# Install required packages
RUN yum -y install bc bridge-utils cmake cmake3 devscripts dkms doxygen dpkg dpkg-dev dpkg-perl elfutils-libelf-devel expect file gettext gcc-c++ libgcc glibc.i686 libcxx-devel ncurses ncurses-base ncurses-libs numactl-devel numactl-libs libssh libunwind-devel libunwind llvm  llvm-libs make openssl openssl-libs openssh openssh-clients pciutils pciutils-devel pciutils-libs python python-pip python-devel pkgconfig pth qemu-kvm re2c rpm rpm-build subversion wget

RUN yum clean all

# Enable the epel repository for fakeroot
RUN yum --enablerepo=extras install -y fakeroot
RUN yum clean all

# On CentOS, install package centos-release-scl available in CentOS repository:
RUN yum install -y centos-release-scl

# Install the devtoolset-7 collection:
RUN yum install -y devtoolset-7
RUN yum install -y devtoolset-7-libatomic-devel devtoolset-7-elfutils-libelf-devel

# Install the ROCm components
ADD driver /root/driver
WORKDIR /root/driver

#====================== for external repo ========================
#RUN yum clean all
#RUN wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | apt-key add -
#RUN sh -c 'echo deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/rocm.list'
#RUN yum-config-manager --add-repo http://repo.radeon.com/rocm/apt/centos/
#RUN yum -y update
#RUN yum install --nogpgcheck -y hsakmt-roct*.rpm hsakmt-roct-dev*.rpm
#RUN yum install --nogpgcheck -y hsa-ext-rocr-dev*.rpm hsa-rocr-dev*.rpm
#RUN yum install --nogpgcheck -y rocm-opencl*.rpm rocm-opencl-devel*.rpm rocm-smi*.rpm rocm-utils*.rpm rocminfo*.rpm  hcc*.rpm atmi*.rpm hip_base*.rpm hip_doc*.rpm hip_hcc*.rpm hip_samples*.rpm hsa-amd-aqlprofile*.rpm rocm-clang-ocl*.rpm
#RUN yum install --nogpgcheck -y rocm-profiler cxlactivitylogger miopen-hip miopengemm rocblas rocrand rocfft hipblas
# =============for internal repo======================
RUN yum clean all
RUN rm -rf /var/cache/yum/*
RUN yum-config-manager --add-repo http://172.27.226.104/artifactory/list/rocm-dkms-release-$rocm_rel-centos/
#RUN yum -y update
RUN yum install --nogpgcheck -y hsakmt-roct* hsakmt-roct-dev*
RUN yum install --nogpgcheck -y hsa-ext-rocr-dev* hsa-rocr-dev*
RUN yum install --nogpgcheck -y rocm-opencl* rocm-opencl-devel* rocm-smi*. rocm-utils* rocminfo*  hcc* atmi* hip_base* hip_doc* hip_hcc* hip_samples* hsa-amd-aqlprofile rocm-clang-ocl* rocm-cmake*
RUN yum install --nogpgcheck -y rocm-profiler cxlactivitylogger miopen-hip miopengemm rocblas rocrand rocfft hipblas rocsparse hipsparse

ENV HCC_HOME=$ROCM_PATH/hcc
ENV HIP_PATH=$ROCM_PATH/hip
ENV OPENCL_ROOT=$ROCM_PATH/opencl
ENV PATH="$HCC_HOME/bin:$HIP_PATH/bin:${PATH}"
ENV PATH="$ROCM_PATH/bin:${PATH}"
ENV PATH="$OPENCL_ROOT/bin:${PATH}"

ARG HCC_HOME=/opt/rocm/hcc
ARG HIP_PATH=/opt/rocm/hip
ARG PATH=$HCC_HOME/bin:$HIP_PATH/bin:$PATH

RUN rm -rf ~/.cache/*
RUN echo "gfx900" >> /opt/rocm/bin/target.lst
RUN echo "gfx906" >> /opt/rocm/bin/target.lst
RUN echo "gfx803" >> /opt/rocm/bin/target.lst

WORKDIR /root/driver

# Install latest cmake and boost 1.59
RUN wget https://cmake.org/files/v3.6/cmake-3.6.2.tar.gz
RUN tar -zxvf cmake-3.6.2.tar.gz
WORKDIR cmake-3.6.2
RUN ./bootstrap --prefix=/usr/local
RUN make
RUN make install
RUN echo "PATH=/usr/local/bin:$PATH:$HOME/bin" >> ~/.bash_profile
RUN cmake --version
WORKDIR /root/driver
RUN rpm -ivh lib64icu42-4.2.1-1mdv2010.0.x86_64.rpm
RUN wget https://bintray.com/vicendominguez/CentOS6/rpm -O /etc/yum.repos.d/bintray-vicendominguez-CentOS6.repo 
RUN yum -y install boost-devel


WORKDIR $HOME

RUN yum -y install gcc gcc-c++ python-pip python-devel atlas atlas-devel gcc-gfortran openssl-devel libffi-devel python3-devel python3-pip python3-wheel python3* --skip-broken

# Use devtoolset env
ENV PATH=/opt/rh/devtoolset-7/root/usr/bin:/opt/rocm/hcc/bin:/opt/rocm/hip/bin:/opt/rocm/bin:/opt/rocm/hcc/bin:${PATH:+:${PATH}}
ENV MANPATH=/opt/rh/devtoolset-7/root/usr/share/man:${MANPATH}
ENV INFOPATH=/opt/rh/devtoolset-7/root/usr/share/info${INFOPATH:+:${INFOPATH}}
ENV PCP_DIR=/opt/rh/devtoolset-7/root
ENV PERL5LIB=/opt/rh/devtoolset-7/root//usr/lib64/perl5/vendor_perl:/opt/rh/devtoolset-7/root/usr/lib/perl5:/opt/rh/devtoolset-7/root//usr/share/perl5/
ENV LD_LIBRARY_PATH=/usr/local/lib:/opt/rh/devtoolset-7/root$rpmlibdir$rpmlibdir32${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
ENV PYTHONPATH=/opt/rh/devtoolset-7/root/usr/lib64/python$pythonvers/site-packages:/opt/rh/devtoolset-7/root/usr/lib/python$pythonvers/
ENV LDFLAGS="-Wl,-rpath=/opt/rh/devtoolset-7/root/usr/lib64 -Wl,-rpath=/opt/rh/devtoolset-7/root/usr/lib"

WORKDIR /root/driver

RUN git clone -b master https://streamhsa:AH64_uh1@github.com/ROCmSoftwarePlatform/rocblas
WORKDIR rocblas
RUN ./install.sh -cd 2>&1 | tee rocblas-build.log

WORKDIR /root/driver
RUN git clone -b master https://streamhsa:AH64_uh1@github.com/ROCmSoftwarePlatform/hipblas
WORKDIR  hipblas
RUN ./install.sh -cd 2>&1 | tee hipblas-build.log

WORKDIR /root/driver
RUN git clone -b master https://streamhsa:AH64_uh1@github.com/ROCmSoftwarePlatform/rocrand.git
WORKDIR rocrand
#RUN sed -i 's/const distribution_func_type\& distribution_func)/const distribution_func_type\& distribution_func) __attribute__((cpu))/g' test/crush/stat_test_common.hpp
RUN rm -rf build
RUN mkdir build
WORKDIR build
#RUN mv /usr/local/lib/libgtest.a /usr/local/lib/libgtest_old.a
RUN CXX=/opt/rocm/hcc/bin/hcc  cmake -DBUILD_TEST=ON -DBUILD_BENCHMARK=ON -DBUILD_CRUSH_TEST=ON -DDEPENDENCIES_FORCE_DOWNLOAD=ON ../.
RUN make -j16 2>&1 | tee rocrand-build.log
RUN make package

WORKDIR /root/driver
RUN git clone -b master https://streamhsa:AH64_uh1@github.com/ROCmSoftwarePlatform/rocfft
WORKDIR rocfft
RUN ./install.sh -cd 2>&1 | tee rocfft-build.log

WORKDIR /root/driver
RUN git clone -b master https://github.com/ROCmSoftwarePlatform/rocsparse.git
WORKDIR /root/driver/rocsparse
RUN ./install.sh -cd 2>&1 | tee rocsparse-build.log

WORKDIR /root/driver
RUN git clone -b master https://github.com/ROCmSoftwarePlatform/hipsparse.git
WORKDIR /root/driver/hipsparse
RUN ./install.sh -cd 2>&1 | tee hipsparse-build.log


WORKDIR /root/driver
RUN cp -rf /root/driver/half.hpp $ROCM_PATH/include
RUN mkdir hip-mlopen
WORKDIR hip-mlopen 
WORKDIR /root/driver/hip-mlopen
RUN git clone -b develop https://streamhsa:AH64_uh1@github.com/AMDComputeLibraries/MLOpen.git
WORKDIR  MLOpen
RUN sed -i 's/gfx803/gfx906/g' CMakeLists.txt 
RUN rm -rf build
RUN mkdir build
WORKDIR build
RUN CXX=/opt/rocm/hcc/bin/hcc cmake -DMIOPEN_TEST_ALL=ON -DMIOPEN_BACKEND=HIP -DMIOPEN_MAKE_BOOST_PUBLIC=ON -DCMAKE_PREFIX_PATH="/opt/rocm/hcc;/opt/rocm/hip" -DCMAKE_CXX_FLAGS="-isystem /usr/include/x86_64-linux-gnu/" ..
RUN make -j16 2>&1 | tee hipmlopen-build.log
RUN make package 2>&1 | tee -a hipmlopen-build.log

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rocm/lib:/opt/rocm/rccl/lib64
ENV PATH=/opt/rocm/bin:$PATH
ENV HCC_HOME=/opt/rocm/hcc
ENV HIP_PATH=/opt/rocm/hip
ENV PATH=$HCC_HOME/bin:$HIP_PATH/bin:$PATH

WORKDIR /root/driver

RUN yum install -y gflags-devel lmdb* glog-devel opencv-devel protobuf-compiler protobuf-devel hdf5-devel compat-db leveldb-devel snappy-devel atlas* blas*

RUN git clone -b hip-centos https://github.com/rocmsoftwareplatform/hipcaffe
WORKDIR /root/driver/hipcaffe
ENV PATH=/opt/rocm/bin:$PATH
ENV LD_LIBRARY_PATH=/opt/rocm/lib:$LD_LIBRARY_PATH
ENV INCLUDE_DIR=/opt/rocm/include
RUN cp Makefile.config.example Makefile.config
RUN make -j16 2>&1 | tee hipcaffe_build.log


RUN ./data/ilsvrc12/get_ilsvrc_aux.sh 2>&1 | tee -a  hipcaffe_build.log
RUN ./scripts/download_model_binary.py models/bvlc_reference_caffenet 2>&1 | tee -a hipcaffe_build.log

RUN ./data/cifar10/get_cifar10.sh 2>&1 | tee -a hipcaffe_build.log
RUN ./examples/cifar10/create_cifar10.sh 2>&1 | tee -a hipcaffe_build.log

RUN ./data/mnist/get_mnist.sh 2>&1 | tee -a hipcaffe_build.log
RUN ./examples/mnist/create_mnist.sh 2>&1 | tee -a hipcaffe_build.log


WORKDIR /root/driver
RUN git clone https://github.com/ROCmSoftwarePlatform/rccl
WORKDIR /root/driver/rccl
RUN mkdir build
WORKDIR /root/driver/rccl/build
RUN CXX=/opt/rocm/bin/hcc cmake ..
RUN make -j8 package
RUN yum install *.rpm


WORKDIR /root/driver
RUN git clone https://streamhsa:AH64_uh1@github.com/ROCmSoftwarePlatform/deepbench
WORKDIR /root/driver/deepbench/code/amd
RUN sed -i 's/-O3/-O3 -I\/opt\/rocm\/include/g' Makefile
RUN make all 2>&1 | tee deepbench_build.log

WORKDIR $HOME
